### ISSUE TITLE
Bug with sending messages.

### ISSUE THREAD

**Issue by PyICoder** [mew/ColourChat#1]
I am not sure if it is a mod conflict but in order for the colors to work for me, I need to be in that chat channel such as Party, then when I say something it has the color.

**Comment by mew** [comment]
Unfortunately, hypixel will filter out colour codes if the message is ran with the command (ie /gc and /pc). Because of this limitation you do have to be in the chat channel to have colour applied to your messages. The only reason it works with the commands at all is because the mod [removes the command part if you're in the respective channel](https://git.io/JJmzG).
